export const PROGRESS_OFFSET_LEFT = 'left'
export const PROGRESS_OFFSET_RIGHT = 'right'
export const PROGRESS_OFFSET_TOP = 'top'
export const PROGRESS_OFFSET_BOTTOM = 'bottom'
export const PROGRESS_OFFSET_NONE = ''

export const PROGRESS_OFFSET_ENUM = {
  PROGRESS_OFFSET_LEFT: PROGRESS_OFFSET_LEFT,
  PROGRESS_OFFSET_RIGHT: PROGRESS_OFFSET_RIGHT,
  PROGRESS_OFFSET_TOP: PROGRESS_OFFSET_TOP,
  PROGRESS_OFFSET_BOTTOM: PROGRESS_OFFSET_BOTTOM,
  PROGRESS_OFFSET_NONE: PROGRESS_OFFSET_NONE,
} as const
